- name: archRox
  hosts: archrox

  tasks:
    - name: Run the equivalent of "pacman -Sy" as a separate step
      community.general.pacman:
        update_cache: true
    - name: Install packages foo from repo
      community.general.pacman:
        name: 
          - neovim
          - vim
          - screen
        state: present
